name: Build PyPy

on:
  push:
    branches:
      - '**'
    paths:
      - 'builder/**'
      - '.github/workflows/build-pypy.yml'
  workflow_dispatch:

env:
  PYPY_BASE: 3.9
  PYPY_VERSION: 7.3.11

jobs:
  Prep:
    runs-on: ubuntu-latest
    name: Prep Docker Container
    permissions:
      contents: read
      packages: write

    steps:

      - name: Login To GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Chmox build script
        run: chmod +x builder/build.sh

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: "builder/"
          push: true
          tags: ghcr.io/cyb3r-jak3/alpine-pypy-builder:${{ env.PYPY_BASE }}-v${{ env.PYPY_VERSION }}-${{ github.sha }}
          build-args: |
            PYPY_BASE=${{ env.PYPY_BASE }}
            BUILD_IMAGE=cyb3rjak3/alpine-pypy:2.7-7.3.11-3.17
          platforms: linux/amd64,linux/arm64/v8
          cache-to: type=gha,mode=max,scope=buildx-alpine-pypy-builder:${{ env.PYPY_BASE }}-v${{ env.PYPY_VERSION }}
          cache-from: type=gha,scope=buildx-alpine-pypy-builder:${{ env.PYPY_BASE }}-v${{ env.PYPY_VERSION }}

  Build:
    runs-on: self-hosted
    name: Run Container
    needs: Prep
    container:
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      image: ghcr.io/cyb3r-jak3/alpine-pypy-builder:3.9-v7.3.11-${{ github.sha }}
      options: --platform linux/amd64
    steps:
      - name: Run Build
        run: /build.sh

      - name: Upload PyPy to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pypy${{ env.PYPY_BASE }}-v${{ env.PYPY_VERSION }}
          path: /tmp/usession-release-pypy${{ env.PYPY_BASE }}-v${{ env.PYPY_VERSION }}-1/build/**.tar.bz2
