name: Build Docker Images

on:
  push:
    branches:
      - '**'
    paths:
      - 'export/**'
      - 'python2.7/**'
      - '.github/workflows/build-docker-images.yml'
      - 'docker-bake.hcl'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  DOCKER_USERNAME: cyb3rjak3

jobs:
  Publish:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        target: ["python-2_7", "alpine-pypy-builder", "alpine-pypy-builder-bootstrap", "alpine-pypy-2_7", "alpine-pypy-3_9", "alpine-pypy-3_10"]
        runner: ["ubuntu-latest", "ubuntu-24.04-arm"]
    steps:
      - uses: actions/checkout@v5

      - name: Login to Docker
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login To GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=false
          images: cyb3rjak3/${{ matrix.target }},ghcr.io/cyb3r-jak3/${{ matrix.target }},mine.jfrog.cyberjake.xyz/${{ matrix.target }}
          labels: |
            org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/docker-alpine-pypy.git
            maintainer=Cyb3r Jak3 git@cyberjake.xyz
            org.opencontainers.image.vendor=cyb3rjak3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.target }}
        uses: docker/bake-action@v6
        with:
          source: .
          files: |
            ${{ steps.meta.outputs.bake-file }}
            ./docker-bake.hcl
          targets: ${{ matrix.target }}-release
          push: ${{ github.ref == 'refs/heads/main' }}
          pull: true
          provenance: true
          sbom: true
          set: |
            *.cache-from=type=registry,ref=ghcr.io/cyb3r-jak3/alpine-pypy-cache:${{ matrix.target }}
            *.cache-to=type=registry,ref=ghcr.io/cyb3r-jak3/alpine-pypy-cache:${{ matrix.target }},mode=max


  Update-DockerHub:
    runs-on: ubuntu-latest
    name: Update DockerHub Descriptions
    needs: Publish
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        repository: ["alpine-pypy", "python-2.7.18", "alpine-pypy-builder"]
    steps:
      - uses: actions/checkout@v5

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@432a30c9e07499fd01da9f8a49f0faf9e0ca5b77 # v4.0.2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: "${{ env.DOCKER_USERNAME }}/${{ matrix.repository }}"