name: Build PyPy

on:
  push:
    branches:
      - '**'
    paths:
      - 'builder/**'
      - '.github/workflows/build-pypy.yml'
  workflow_dispatch:

env:
  ALPINE_VERSION: 3.17
  BUILDER_IMAGE_TAG: ghcr.io/cyb3r-jak3/alpine-pypy-builder-workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Prep:
    runs-on: ubuntu-latest
    name: Prep Docker Container
    steps:

      - uses: actions/checkout@v3

      - name: Login To GitHub
        uses: docker/login-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: "builder/"
          tags: ${{ env.BUILDER_IMAGE_TAG }}:${{ env.ALPINE_VERSION }}-${{ github.sha }}
          build-args: |
            BUILD_IMAGE=ghcr.io/cyb3r-jak3/alpine-pypy:2.7-7.3.11-3.17
          cache-to: type=gha,mode=max,scope=buildx-alpine-pypy-builder:${{ env.ALPINE_VERSION }}-${{ github.sha }}
          cache-from: type=gha,scope=buildx-alpine-pypy-builder:${{ env.ALPINE_VERSION }}-${{ github.sha }}
          platforms: linux/amd64, linux/arm64
          push: true
      
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: builder_image
      #     path: /tmp/image.tar
      #     if-no-files-found: error
      #     retention-days: 1

  Build:
    runs-on: ubuntu-latest
    name: Run Container
    needs: Prep
    strategy:
      fail-fast: true
      matrix:
        PYPY_BASE: ["2.7", "3.8", "3.9"]
        PYPY_VERSION: ["7.3.11"]
        PLATFORM: ["amd64", "arm64"]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Download builder image from previous workflow
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: builder_image
      #     path: /tmp/image.tar

      - name: Load Docker images from previous workflows
        run: docker load --input /tmp/image.tar/image.tar

      - name: Run Build
        run: |
          PYPY_SHA256SUM=$(curl -s https://api.cyberjake.xyz/pypy/checksums/pypy${{ matrix.PYPY_BASE }}-v${{ matrix.PYPY_VERSION }}-src.tar.bz2 | jq --raw-output .results.checksum)
          echo "${PYPY_SHA256SUM}"
          docker run --platform linux/${{ matrix.PLATFORM }}  -v $(pwd)/tmp:/tmp -e PYPY_BASE=${{ matrix.PYPY_BASE }} -e PYPY_VERSION=${{ matrix.PYPY_VERSION }} -e PYPY_SHA256SUM="${PYPY_SHA256SUM}" ${{ env.BUILDER_IMAGE_TAG }}:${{ env.ALPINE_VERSION }}-${{ github.sha }}

      - name: Upload PyPy to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pypy-${{ matrix.PLATFORM }} 
          path: ./tmp/usession-release-pypy${{ matrix.PYPY_BASE }}-v${{ matrix.PYPY_VERSION }}-1/build/**.tar.bz2
