name: Build PyPy

on:
  push:
    branches:
      - '**'
    paths:
      - 'builder/**'
      - '.github/workflows/build-pypy.yml'

env:
  PYPY_BASE: 3.9
  PYPY_VERSION: 7.3.11

jobs:
  Prep:
    runs-on: self-hosted
    name: Prep Docker Container

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Build Builder Image
        run: |
          cd builder/ && chmod +x build.sh && docker build --platform linux/amd64 --build-arg PYPY_BASE=${{ env.PYPY_BASE }} -t alpine-pypy-builder:${{ env.PYPY_BASE }}-${{ env.PYPY_VERSION }}-bootstrap-${{ github.sha }} .

  Build:
    runs-on: self-hosted
    name: Run Container
    needs: Prep
    env:
      PYPY_BASE: 3.9
      PYPY_VERSION: 7.3.11
    container:
      image: alpine-pypy-builder:${{ env.PYPY_BASE }}-${{ env.PYPY_VERSION }}-bootstrap-${{ github.sha }}
      # volumes:
      #   - "./pypy:/tmp"
      options: /bin/sh
    steps:
      - name: Run Build
        run: /build.sh

      - name: Upload PyPy to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pypy${{ env.PYPY_BASE }}-v${{ env.PYPY_VERSION }}
          path: ./tmp/usession-release-pypy${{ env.PYPY_BASE }}-v${{ env.PYPY_VERSION }}-1/build/**.tar.bz2
