name: Build Docker Images

on:
  push:
    branches:
      - '**'
    paths:
      - 'export/**'
      - 'python2.7/**'
      - '.github/workflows/build-docker-images.yml'
      - 'docker-bake.hcl'


jobs:
  Publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["python-2.17", "alpine-pypy"]
    steps:
      - uses: actions/checkout@v3

      # - name: Login to Docker
      #   uses: docker/login-action@v2
      #   if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Login To GitHub
      #   uses: docker/login-action@v2
      #   if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.CR_PAT }}

      # - name: Login To GitLab
      #   uses: docker/login-action@v2
      #   if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      #   with:
      #     registry: registry.gitlab.com
      #     username: ${{ secrets.GITLAB_USER }}
      #     password: ${{ secrets.GITLAB_TOKEN }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=false
          images: cyb3rjak3/${{ matrix.target }},ghcr.io/cyb3r-jak3/${{ matrix.target }}
          labels: |
            org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/docker-alpine-pypy.git
            maintainer=Cyb3r Jak3 git@cyberjake.xyz
            org.opencontainers.image.vendor=cyb3rjak3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Build
        uses: docker/bake-action@v2.3.0
        with:
          files: |
            ${{ steps.meta.outputs.bake-file }}
            ./docker-bake.hcl
          targets: ${{ matrix.target }}-release
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          set: |
            *.cache-from=type=gha,scope=buildx-${{ matrix.target }}
            *.cache-to=type=gha,mode=max,scope=buildx-${{ matrix.buildType }}-${{ matrix.target }}


