name: Build Docker Images

on:
  push:
    branches:
      - '**'
    paths:
      - 'export/**'
      - 'python2.7/**'
      - '.github/workflows/build-docker-images.yml'
      - 'docker-bake.hcl'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_USERNAME: cyb3rjak3

jobs:
  Publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["python-2_7", "alpine-pypy-builder", "alpine-pypy-builder-bootstrap", "alpine-pypy-2_7", "alpine-pypy-3_8", "alpine-pypy-3_9"]
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker
        uses: docker/login-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login To GitHub
        uses: docker/login-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=false
          images: cyb3rjak3/${{ matrix.target }}
          labels: |
            org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/docker-alpine-pypy.git
            maintainer=Cyb3r Jak3 git@cyberjake.xyz
            org.opencontainers.image.vendor=cyb3rjak3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build ${{ matrix.target }}
        uses: docker/bake-action@v2
        with:
          files: |
            ${{ steps.meta.outputs.bake-file }}
            ./docker-bake.hcl
          targets: ${{ matrix.target }}-release
          push: ${{ github.ref == 'refs/heads/main' }}
          set: |
            *.cache-from=type=gha,scope=buildx-${{ matrix.target }}
            *.cache-to=type=gha,mode=max,scope=buildx-${{ matrix.target }}


  Update-DockerHub:
    runs-on: ubuntu-latest
    name: Update DockerHub Descriptions
    needs: Publish
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        repository: ["alpine-pypy", "python-2.7.18", "alpine-pypy-builder"]
    steps:
      - uses: actions/checkout@v3

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: "${{ env.DOCKER_USERNAME }}/${{ matrix.repository }}"