name: Generate Release

on:
    push:

jobs:
  generate-release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    env:
      BASE: "2.7,3.9,3.10"
      VERSION: "7.3.14"
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Release Info
          run: |
              echo "::notice title=PYPY_BASE::${{ env.BASE }}"
              echo "::notice title=PYPY_VERSION:: ${{ env.VERSION }}"

        - name: Prep Release
          run: python .github/release.py
          env:
            PYPY_BASE: ${{ env.BASE }}
            PYPY_VERSION: ${{ env.VERSION }}

        - name: Generate Checksums
          run: |
            ls -la *.tar.bz2*
            sha256sum *.tar.bz2 > checksums.sha256
            gpg --no-tty --keyserver hkps://keys.openpgp.org --auto-key-locate keyserver --locate-keys releases@cyberjake.xyz
            find . -iname "*.tar.bz2" -type f -exec  bash -c "echo verifying {}; gpg --quiet --verify {}.sig {} " \;